### PR TITLE
feat: added og tags

### LINKED ISSUE #1: Feat: OG Image
@championswimmer
I was watching the podcast you had with Kailash Nadh. There you mentioned this project and you wanted to add a feature wherein people can see the time zone from the image preview itself. 
Can I take up this and try developing it?

### PR DESCRIPTION
**Pull request by swapnadeepmohapatra**
This fixes #1 

It uses [@egoist/vue-head](https://www.npmjs.com/package/@egoist/vue-head) to solve this issue. 

## This is how the meta tags of `http://sharetime.zone/America/Chicago/now` look like

```HTML
  <title>Time at America/Chicago is 07:51:11 AM</title>
  <meta property="og:url" content="http://sharetime.zone/">
  <meta name="description" content="Time right now at America/Chicago is 07:50:53 AM">
  <meta name="keywords" content="sharetime">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Time at America/Chicago is 07:50:53 AM">
  <meta property="og:image" content="https://og-image-sharetime.vercel.app/now.png?desc=America/Chicago&amp;desc=07:50:53 AM">
  <meta property="og:description" content="Time right now at America/Chicago is 07:50:53 AM">
  <meta property="og:site_name" content="sharetime.zone">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Time at America/Chicago is 07:50:53 AM">
  <meta name="twitter:description" content="Time right now at America/Chicago is 07:50:53 AM">
  <meta name="twitter:image:src" content="https://og-image-sharetime.vercel.app/now.png?desc=America/Chicago&amp;desc=07:50:53 AM">
```

## Example of the OG Image:

image

image

### CODE REVIEW

**Comment by swapnadeepmohapatra** [comment]
Okay, this is strange. The deployed preview is not showing any of the meta tags. Lemme check it.

**Comment by championswimmer** [comment]
loved this PR, I'll try to modify this and adapt it, rather than directly merge it as a few things have changed on the project. Will make you the author of the modified commit so you get the appropriate accrediation of your work :)

**Comment by championswimmer** [comment]
loved this PR, I'll try to modify this and adapt it, rather than directly merge it as a few things have changed on the project. Will make you the author of the modified commit so you get the appropriate accrediation of your work :)

**Comment by championswimmer** [comment]
loved this PR, I'll try to modify this and adapt it, rather than directly merge it as a few things have changed on the project. Will make you the author of the modified commit so you get the appropriate accreditation of your work :)

**Comment by championswimmer** [comment]
loved this PR, I'll try to modify this and adapt it, rather than directly merge it as a few things have changed on the project. Will make you the author of the modified commit so you get the appropriate accreditation of your work :)

**Comment by championswimmer** [comment]
loved this PR, I'll try to modify this and adapt it, rather than directly merge it as a few things have changed on the project. Will make you the author of the modified commit so you get the appropriate accreditation of your work :)

**Pull request closed without merging**
